spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ToDoList
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.todolist.todolist

server:
  port: 8090